### ISSUE TITLE
diego cell upgrade limit on starting containers

### ISSUE THREAD

**Issue by gberche-orange** [cloudfoundry/docs-cf-admin#126]
The page https://docs.cloudfoundry.org/adminguide/diego-cell-upgrade.html#limitations-considerations mentions limit on "started" containers, whereas it should read "starting" containers

> If too many app instances are **started** at once, then the load of these starts on the rest of the system can cause other applications that are already running to crash and be rescheduled. These events can result in a cascading failure.
> 
> To prevent overload, Cloud Foundry provides two major throttle configurations:
> 
>     The maximum number of starting containers that Diego can start in Cloud Foundry: This is a deployment-wide limit. The default value and ability to override this configuration depends on the version of Cloud Foundry deployed. For information about how to configure this setting, 
>     see the Setting a Maximum Number of **Started** Containers topic.

**Comment by gberche-orange** [comment]
@emalm can you please confirm my understanding and wording fix in the two PRs?

**Comment by emalm** [comment]
Thanks, @gberche-orange! Yes, that's correct, and the "starting" language is consistent with the [`diego.auctioneer.starting_container_count_maximum ` property on the auctioneer job](https://github.com/cloudfoundry/diego-release/blob/v2.15.0/jobs/auctioneer/spec#L53-L55) that controls that limit.

Looks like the page title at https://github.com/cloudfoundry/docs-cf-admin/blob/28baef2316b012e1d66f02a624d2ab6530dc31b1/max-container-starts.html.md.erb#L2 should also change to say `Starting` instead of `Started`.

**Comment by mlimonczenko** [comment]
Thanks for the PR, @gberche-orange, and for the context, @emalm. I'm going to close out this issue.
